### ISSUE TITLE
Telemetry filter rendered useless

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1392]
## Describe the bug
The "Logs" page in the UI has a filter capability, but it automatically refreshes itself, periodically.

## To Reproduce
1. Go to the "Logs" page of the UI
2. Use the "filter" input field to filter out some telemetries
3. Wait...
4. Watch as telemetries that should be filtered out magically reappear

## Screenshots
![telemetry-refresh](https://user-images.githubusercontent.com/19957806/127781508-845c18c3-1d74-4981-8d53-919ba7b2c119.gif)

## Machine version (please complete the following information):
 - OS: Linux

**Comment by ilija-lazoroski** [comment]
It is calling `render()` periodically due to the nature of the component which is `Component` as explained [here.](https://reactjs.org/docs/react-api.html#reactpurecomponent) . 

Possible solution would be to implement `shouldComponentUpdate()` and check if there is new telemetry data and rerender only if there is.
