### ISSUE TITLE
Encryptor doesn't work with UTF-8 characters

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#1490]
## Describe the bug
Datastore encryptor breaks when a UTF-8 character is encountered: 
![image](https://user-images.githubusercontent.com/36815064/134904020-504584cb-e94e-4289-ad4b-25710939b802.png)

This is an important bug, because gathered credentials might contain unicode characters, user can't submit common passwords, for e.g. "slaptažodis" means password in Lithuanian and might be common in Lithuanian networks:
![image](https://user-images.githubusercontent.com/36815064/134904474-48d92508-015a-4ab9-bd2b-3bb9bfbc52f5.png)

## Tasks
- [ ] We should write unit tests that reproduce the issue and then swap out the padding functions with functions from `Crypto.Util.Padding`. (0.25d) - @shreyamalviya

**Comment by mssalvatore** [comment]
This is caused by incorrect assumptions in the padding function.

https://github.com/guardicore/monkey/blob/96c525d6569494d08b1de069e794ae46d63579b2/monkey/monkey_island/cc/server_utils/encryption/key_based_encryptor.py#L40-L47

The padding function uses `len(message)`, but this assumes that all characters are 1 byte. Unicode characters can be more than 1 byte.

![image](https://user-images.githubusercontent.com/19957806/134908335-2fff0e36-90d3-4117-8ea8-d4ab7d700932.png)
