### ISSUE TITLE
Copy file failed: [Errno 2] No such file or directory: 'C:\\Program Files\\Guardicore\\Monkey Island\\monkey\\monkey_island\\cc\\binaries\\monkey-windows-64.exe'

### ISSUE THREAD

**Issue by Rhoenit** [guardicore/monkey#1568]
## Describe the bug

I can run it once and after start over / reset the environment I just get the error: Copy file failed: [Errno 2] No such file or directory: 'C:\\Program Files\\Guardicore\\Monkey Island\\monkey\\monkey_island\\cc\\binaries\\monkey-windows-64.exe' 

## To Reproduce

I didn´t use local network scan and set a Windows target directory.

run the Monkey from Island

Start over -> reset the environment

now I can´t run another monkey and get this error code.

## Expected behavior

the monkey should run.

## Screenshots.
![monkeyerror](https://user-images.githubusercontent.com/78480832/139876587-91efdd1c-6997-4430-9761-a6f87c1eb6ff.PNG)

## Machine version (please complete the following information):
 Windows 
-----------------------------

And is there a way to decrypt the files or do I have to rename it and use the monkey again?

**Comment by mssalvatore** [comment]
Like it says in the error dialog, something has deleted those files. Do you have an antivirus running, such as Windows Defender? If so. you'll need to tell your antivirus to ignore those files, as [they're not malicious](https://www.guardicore.com/infectionmonkey/docs/faq/#is-the-infection-monkey-a-malwarevirus).

You can download the binaries from [here](https://github.com/guardicore/monkey/releases/tag/v1.12.0), but you'll need to disable whatever is deleting them, otherwise you'll get this error again.

**Comment by Rhoenit** [comment]
Thank you. 

I didn´t use it since the last update and now Windows Defender blocked it again :D

**Comment by mssalvatore** [comment]
Yeah, it's a problem we're working on. There's no simple solution, though.
