### ISSUE TITLE
Fix failing windows build

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1630]
## Tasks
- [x] Investigate whether or not the Island is running out of disk space (0d) @ilija-lazoroski 
- [x] Find any other issues that are preventing a successful test and fix them (0d) @ilija-lazoroski

**Comment by ilija-lazoroski** [comment]
Soo yep, the island was running out of space. The machine had around 4Gb left of space which were not enough to run all the BB tests. Cleaning up `Temp` fix it and release around 7Gb which is enough. We need to keep an eye of that machine about filling out the disk space. 

Another issue was the Jenkins success/fail code. The powershell script exited with True/False for success/fail but AppImage and Docker both were using 0/1 as exit codes. That is fixed in Jenkins.
