### ISSUE TITLE
SystemInfoCollector refactor PDR

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#1672]
# Spike

## Objective

The goal and purpose of `SystemInfoCollector`'s is not clearly defined enough to allow it to be used for plugins. Additionally, the majority of `SystemInfoCollector`s have been removed since the info they collected was never used (#1535) or because they don't fit Monkey's mission (#1669). The remaining info collectors are SSH, Mimikatz, AWS, and Process List Collector.

The proposed solution is to change the `SystemInfoCollector` interface to be `CredentialsCollector` and refactor the ProcessListCollector to be a `PostBreachAction`. Further investigation is needed to determine whether or not the AWS collector is actually required. If it is, it can be moved to the Agent as part of the agent refactor project.

Consider the architectural implications of making this change. Create a PDR that describes these changes or proposes an alternative.

## Scope
Time boxed to 3 days.

## Output
A PDR.

## Tasks
- [ ] Create a PDR for these changes (0.75d) - @VakarisZ

**Comment by VakarisZ** [comment]
There are three things to consider:

## 1. AWS collector

Aws collector is used in AWS security hub findings. The two options are to delete or to refactor. 

### Delete

I couldn't find any information about the usage of the exported findings. I will update when/if I get the stats, but removal is not a likely outcome for now.

### Refactor

Aws collector needs to be moved from `\infection_monkey\monkey\common\cloud\aws` to the agent codebase. The master will use it to identify the environment it's running in.

## 2. Credential collectors

SSH collector and mimikatz collector are essentially credential collectors. Credential collector plugin should be instantiated in case we find more ways to collect credentials. Preliminary diagram:
![image](https://user-images.githubusercontent.com/36815064/151826439-4dec28ab-e246-4903-bcc6-6cc1b2f1e227.png)

## 3. Process list collector

Process list collected by process list collector is used to assess if AV is running and display it in the zero trust report. The two options are again, to remove it or to refactor:

### Delete

The AV detection method is flawed, the AV list is probably outdated and incomplete, thus ZT report is sometimes incorrect.

### Refactor

TODO: elaborate, investigate how hard it is to detect if AV is running
The collector could be refactored into a post-breach action. We would need to refactor the collector, improve the AV process list and refactor the back end to pull data from post breach telemetry rather than system info.

**Comment by VakarisZ** [comment]
## More specific decisions:

### 1. AWS collector

For now, it's best to just send the telemetry with the required AWS info if it's running on AWS from the agent.

monkey.py:
```
    def start(self):
        ...

        should_stop = ControlChannel(WormConfiguration.current_server, GUID).should_agent_stop()
        if should_stop:
            logger.info("The Monkey Island has instructed this agent to stop")
            return

        if InfectionMonkey._is_upgrade_to_64_needed():
            self._upgrade_to_64()
            logger.info("32 bit Agent can't run on 64 bit system.")
            return



        if running_on_aws():
                report_aws_env()



        self._setup()
        self._master.start()
```

aws_environment_check.py
```
def running_on_aws():
    return AwsInstance().is_instance()

def report_aws_env():
    EnvironmentTelemetry(AwsInstance())
```


### 2. Credential collectors
Credentials should be sent one by one:
![credential_collectors2 vpd](https://user-images.githubusercontent.com/36815064/152377534-183456c3-568e-48ef-81ef-84eb18fe70d0.jpg)

### 3. Process list collector

The fastest solution is to just refactor to PBA and not change anything else.

**Comment by mssalvatore** [comment]
On the topic of serialization, here's a code snippet that could be useful in the future: 
![image](https://user-images.githubusercontent.com/19957806/152454347-4ee7803e-6f4d-4e5b-993e-1288f4269c01.png)

**Comment by mssalvatore** [comment]
On the topic of serialization, here's a code snippet that could be useful later on: 
![image](https://user-images.githubusercontent.com/19957806/152454434-cb6088ab-bc02-4c11-a220-fb412de22b30.png)

**Comment by VakarisZ** [comment]
Split up into #1697 , #1696 and #1695 , AV detection suggestions moved to #986
