### ISSUE TITLE
Send network info telemetry

### ISSUE THREAD

**Issue by ilija-lazoroski** [guardicore/monkey#1720]
**Is your feature request related to a problem? Please describe.**
All system info collectors included network_info in telemetries. As we removed some of them and refactor the others we need to send the network_info telemetry separately. 

https://github.com/guardicore/monkey/blob/f572e59b7f731378b6943c32535024b4b41303bd/monkey/monkey_island/cc/services/telemetry/processing/system_info.py#L46-L50

**Describe the solution you'd like**
Create network info telemetry and make sure it is processed. Master collects and send telemetry to the Island. 

**Describe alternatives you've considered**
Please describe alternative solutions or features you have considered.

**Comment by mssalvatore** [comment]
When the agent registers with the Island, it sends the monkey's guid and IP address.
https://github.com/guardicore/monkey/blob/49f1675b388ad77096073708cb57c46612fd6c75/monkey/infection_monkey/control.py#L39-L55

The Island can look up the IP by using the GUID, rather than sending separate telemetry.
https://github.com/guardicore/monkey/blob/49f1675b388ad77096073708cb57c46612fd6c75/monkey/infection_monkey/control.py#L158-L175

**Comment by VakarisZ** [comment]
Correct, issue closed
