### ISSUE TITLE
Windows agent is not deleted after completition

### ISSUE THREAD

**Issue by ilija-lazoroski** [guardicore/monkey#1763]
## Describe the bug
When running the monkey agent on windows system, the agent is not deleted after the execution is finished.
Possible cause is that we are using `subprocess.Popen` to launch a command that waits and then deletes the binary, but somewhere we exit the agent which kills the Popen execution and the agent is never deleted.

## To Reproduce
1. Run the Monkey Agent from executable
2. Check if the executable is deleted

## Expected behavior
The agent should be removed after execution.

## Task

- [ ] Investigate and solve it (0.5d) @ilija-lazoroski 

## Screenshots
![image](https://user-images.githubusercontent.com/15820737/156781882-0765de36-9096-4d8d-abd0-90b3234e2eb2.png)

## Machine version (please complete the following information):
 - OS: Windows

**Comment by mssalvatore** [comment]
Using [the `at` command](https://docs.microsoft.com/en-us/troubleshoot/windows-client/system-management-components/use-at-command-to-schedule-tasks) instead of [the current implementation](https://github.com/guardicore/monkey/blob/c6e80b6689e185c921087d5cf54fbecf4bef5dd7/monkey/infection_monkey/model/__init__.py#L27-L30) might resolve the issue and also be cleaner.

**Comment by mssalvatore** [comment]
`[DeleteFileA](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-deletefilea)` might be the best solution.

>The DeleteFile function marks a file for deletion on close. Therefore, the file deletion does not occur until the last handle to the file is closed. Subsequent calls to [CreateFile](https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-createfilea) to open the file fail with ERROR_ACCESS_DENIED.
