### ISSUE TITLE
Agents do not self-remove on mssql-16

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2023]
## Describe the bug
Agents do not self-remove on the mssql-16 machine in GCP after propagation is complete.

## To Reproduce
1. Run an MSSQL test in GCP
2. View C:\Windows\Temp
4. See stale agents polluting the folder.

**Comment by ilija-lazoroski** [comment]
We have some [ACCESS_DENIED](https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-) error:

<img width="1375" alt="image" src="https://user-images.githubusercontent.com/15820737/204487111-b14dcfe8-7e38-4ba3-98d4-296724e00dbb.png">

<img width="254" alt="image" src="https://user-images.githubusercontent.com/15820737/204490220-937bf503-f08a-45b7-a701-58d9c373ee31.png">

**Comment by VakarisZ** [comment]
This is happening because MSSQL server is able to create, but not delete files in `C:\windows\temp`. There's no silver bullet for permission issues. We could check the permissions of the folder prior to uploading the agent. But what if we don't have "delete" permissions anywhere? We don't propagate? It would also complicate the remote code execution as we'd have to add permission checking and directory list logic. 

I think the best solution to somewhat make the permission issues less likely is to use `%homedrive%%homepath%\AppData\Local\Temp\` path for our binaries. That's what pythons' `tempfile` package does. It starts with `%homedrive%%homepath%\AppData\Local\Temp\` and only then tries `%SYSTEMROOT%\Temp`. Making this change would improve the likelihood of binaries getting deleted and would put all of the artefacts (logs and binaries) in the same place.

What we do ATM is just straight up use `C:\Windows\temp\`. The end result is agents and logs being stored in different directories and #350

**Comment by VakarisZ** [comment]
This is essentially the same issue as #350, closing
