### ISSUE TITLE
Island never marks monkeys as dead without a request

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#210]
**Describe the bug**
If monkey island never gets a request from monkey that monkey is shutting down, the monkey is shown as alive indefinitely.

**To Reproduce**
1. Launch the monkey island
2. Launch the monkey and kill it mid-execution

**Expected behavior**
Island should check if monkey is still alive or simply have a time limit on waiting for response from monkey before deeming it dead.

**Comment by shivank1234** [comment]
Can I try this one?

**Comment by ShayNehmad** [comment]
Planning: 
* Root cause might be overlapping responsibilities in IM and MI comm channels. 
* Solution must include server state, which complicated things: 
** Maybe based on mongodb state or something like redis expiry
** Maybe based on actual backend task engine
** ...

Todo: 
- [ ] Set up local test environment - one island machine, one monkey machine, and one monkey minefield machine. 
- [ ] Read relevant code segments and write a DDR

**Comment by ShayNehmad** [comment]
is_any_monkey_alive

**Comment by ShayNehmad** [comment]
Summery planning session with @itaymmguardicore :

 * Create a plan of creating a DAL in python which is testable and independent from the mongo impl
 * Emphesis - Solution that will coexist with the current DAL (which is integrated with the code)
 * Find something like mongoose 
 * Time evalutaion
 * List all places in code which are relevant to "is monkey dead"
