### ISSUE TITLE
Infection map doesn't work properly 

### ISSUE THREAD

**Issue by dberuben** [guardicore/monkey#222]
**Describe the bug**
infection map is a random white page.

**To Reproduce**
issue with Firefox / safari / Chrome
https://URL//infection/map

**Expected behavior**
infection map up and running 

**Machine version(please complete the following information):**
monkey island is deploying in a k8s cluster using helm.

**Error give 500**
> url = https://URL/api/telemetry-feed?timestamp=null

`2018-12-03 13:42:37,118 - app.py:1761 - log_exception() - ERROR - Exception on /api/telemetry-feed [GET]
Traceback (most recent call last):
  File "/var/monkey/monkey_island/bin/python/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/monkey/monkey_island/bin/python/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/monkey/monkey_island/bin/python/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/var/monkey/monkey_island/bin/python/local/lib/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/var/monkey/monkey_island/bin/python/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/var/monkey/monkey_island/cc/auth.py", line 49, in decorator
    return fn(*args, **kwargs)
  File "/var/monkey/monkey_island/cc/resources/telemetry_feed.py", line 28, in get
    'telemetries': [TelemetryFeed.get_displayed_telemetry(telem) for telem in telemetries],
  File "/var/monkey/monkey_island/cc/resources/telemetry_feed.py", line 38, in get_displayed_telemetry
    'hostname': NodeService.get_monkey_by_guid(telem['monkey_guid'])['hostname'],
TypeError: 'NoneType' object has no attribute '__getitem__'
2018-12-03 13:42:37,119 - wsgi.py:374 -       _log() - ERROR - 500 GET /api/telemetry-feed?timestamp=null (10.201.198.147) 4.76ms`

**Comment by dberuben** [comment]
i'm using dev branch

**Comment by itaymmguardicore** [comment]
Hey @dberuben,

First of all sorry for the time it took me to respond, and thank you for reporting the issue.

It seems like the island is getting an exception since for some telemetry, the line: `NodeService.get_monkey_by_guid(telem['monkey_guid'])` returns None.

This seems odd because whenever a monkey sends a telemetry to the island, the monkey should already have an entry in the 'monkey' collection on mongoDB.

My guess is the problem is one of the following:
1. If you manually changed the DB it might be the issue
2. There's a bug either on the monkey or on the island during the initialization of the monkey where it first reports it started running
3. Some very unlikely race condition

To better understand what happened, it could help if you answer the following:
1. Does the issue reproduce? If it does, does it reproduce on simpler environments? (Windows 10, Ubuntu 16.04)
2. Do you still have the mongoDB database used during the bug? If so, it can be very helpful for the understanding of the issue.
3. Do you have the island logs or the monkey logs?

Regards,
Itay Mizeretz, GuardiCore Labs

**Comment by dberuben** [comment]
This issue is from an fresh install with `FROM ubuntu:xenial`, clean mongodb.

1 - no manual change on the Database
2 - No issue during the initialization monkey

same logs as above.

`2018-12-03 13:42:37,118 - app.py:1761 - log_exception() - ERROR - Exception on /api/telemetry-feed [GET] Traceback (most recent call last): File "/var/monkey/monkey_island/bin/python/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request rv = self.dispatch_request() File "/var/monkey/monkey_island/bin/python/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/var/monkey/monkey_island/bin/python/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 480, in wrapper resp = resource(*args, **kwargs) File "/var/monkey/monkey_island/bin/python/local/lib/python2.7/site-packages/flask/views.py", line 88, in view return self.dispatch_request(*args, **kwargs) File "/var/monkey/monkey_island/bin/python/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 595, in dispatch_request resp = meth(*args, **kwargs) File "/var/monkey/monkey_island/cc/auth.py", line 49, in decorator return fn(*args, **kwargs) File "/var/monkey/monkey_island/cc/resources/telemetry_feed.py", line 28, in get 'telemetries': [TelemetryFeed.get_displayed_telemetry(telem) for telem in telemetries], File "/var/monkey/monkey_island/cc/resources/telemetry_feed.py", line 38, in get_displayed_telemetry 'hostname': NodeService.get_monkey_by_guid(telem['monkey_guid'])['hostname'], TypeError: 'NoneType' object has no attribute '__getitem__' 2018-12-03 13:42:37,119 - wsgi.py:374 - _log() - ERROR - 500 GET /api/telemetry-feed?timestamp=null (10.201.198.147) 4.76ms`

**Comment by itaymmguardicore** [comment]
Hey @dberuben ,

We've just fixed this bug.

This issue occurs whenever the 'telemetry' collection has entries with 'monkey_guid' fields which don't have matching entries on the 'monkey' collection. This is most commonly caused by running a monkey, resetting the island's data (From the 'Start Over' button) before the monkey finished its run, and the monkey communicating with the island.

You can checkout the 'develop' branch or wait for the upcoming version to be released which should be soon enough.

If you're still encountering this issue or others, please let us know

**Comment by dberuben** [comment]
cool Thank you :)
