### ISSUE TITLE
Investigate plugins using multiprocessing on Windows

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#2563]
# Spike

## Objective

Discover and document any risks when using multiprocessing for plugins on Windows

## Scope
Python's multiprocessing library behaves differently on Windows and Linux. Prove that the multiprocessing approach behaves as expected on Windows. Document the differences and make the necessary modifications to the prototype.

## Output

- A brief summary of the differences between Windows and Linux with respect to multiprocessing. Links to more details.
- Modifications to the multiprocessing prototype that are required for the prototype to work on Windows.

**Comment by ilija-lazoroski** [comment]
Multiprocessing on Linux and Windows (Mac works the same as Windows) is different and that difference is not minor. It comes with some boundaries for which we need to keep an eye.

Blog post: https://www.pythonforthelab.com/blog/differences-between-multiprocessing-windows-and-linux/
Date: June 13, 2020

## Forked vs. Spawn processes
First, comes the difference between how processes are started. On Linux when we start a child process, the process is `Forked` which means that the child process inherits the memory state from the parent process. While on Windows ( and by default on Mac) when we start a child process. the process is `Spawned` which means that a new interpreter starts and the code reruns.

### Example
```python
import multiprocessing as mp
from time import sleep


print('Before defining simple_func')

def simple_func():
    print('Starting simple func')
    sleep(1)
    print('Finishing simple func')


if __name__ == '__main__':
    p = mp.Process(target=simple_func)
    p.start()
    print('Waiting for simple func to end')
    p.join()
```

Linux output:
<img width="427" alt="image" src="https://user-images.githubusercontent.com/15820737/201335081-04e6ff54-5557-48d2-8e99-1df318d147e0.png">

Windows output:
<img width="688" alt="image" src="https://user-images.githubusercontent.com/15820737/201335147-cc6b4979-6af7-4ba4-9f8d-21b948b2b60f.png">

Mac output (Same as Windows):
<img width="508" alt="image" src="https://user-images.githubusercontent.com/15820737/201335391-0f756eb8-80d3-4316-ad76-a6d2943eca74.png">


Notice the second `Before defining simple_func` when running on Windows (Mac).

Now the printing may not be terrifying but what if we have some calculation or data modification:
```python
import multiprocessing as mp
import random

val = random.random()

def simple_func():
    print(val)


if __name__ == '__main__':
    print('Before multiprocessing: ')
    simple_func()
    print('After multiprocessing:')
    p = mp.Process(target=simple_func)
    p.start()
    p.join()
```

Linux output:
<img width="432" alt="image" src="https://user-images.githubusercontent.com/15820737/201337597-b010d608-8373-4b7e-ad9a-829a95b4e27e.png">

Windows output:
<img width="691" alt="image" src="https://user-images.githubusercontent.com/15820737/201337644-a20798d3-fb7a-4409-a380-ac1a13db216a.png">


## Lets see what happens if we using classes

We will see the case where try and write to a file in the system.

```python
import multiprocessing as mp


class MyClass:
    def __init__(self, i):
        self.i = i
        self.file = open(f'{i}.txt', 'w')

    def simple_method(self):
        print('This is a simple method')
        print(f'The stored value is: {self.i}')

    def mp_simple_method(self):
        self.p = mp.Process(target=self.simple_method)
        self.p.start()

    def wait(self):
        self.p.join()
        self.file.close()


if __name__ == '__main__':
    my_class = MyClass(1)
    my_class.mp_simple_method()
    my_class.wait()
```

Linux output:
<img width="387" alt="image" src="https://user-images.githubusercontent.com/15820737/201338488-b70dda13-a7de-4c3c-bf56-2b7c7ec63a5e.png">

Windows output:
<img width="708" alt="image" src="https://user-images.githubusercontent.com/15820737/201338662-a4a033ce-ea44-4fc7-af8d-57e7c288b794.png">

Spawning the process using classes means that the object must be pickable. If we have a class or attribute of a class that is not pickable then we can't spawn a process.

## Make Linux work like Windows (just for easy testing) 🥸 

We can use a method from multiprocessing so we can replicate how Windows are spawning processes by using `[multiprocessing.set_start_method](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.set_start_method)('spawn')`. The class example on Linux but using `spawn`:

<img width="649" alt="image" src="https://user-images.githubusercontent.com/15820737/201339760-fbe059e3-c5e9-471b-a107-2f78ea54b08d.png">

Linux can become Windows but other way around is not possible. The multiprocessing documentation for `set_start_method` shows that we can use `fork`, `spawn` and `forkserver` as starting methods.

Now I would guess that `fork` will create Forked processes in Windows but the crucial thing is that Windows doesn't support the [fork-exec model](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwi89pjfj6b7AhUXRvEDHWolAAEQFnoECBAQAw&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FFork%25E2%2580%2593exec&usg=AOvVaw0jtSbWOFgjhZwbf91yoCx2) and it doesn't have anything near fork. On other hand [Cygwin has some implementation of fork](https://stackoverflow.com/questions/985281/what-is-the-closest-thing-windows-has-to-fork) that we can use on Windows but by the [answer on StackOverflow](https://stackoverflow.com/questions/17300551/how-to-run-python-script-with-os-fork-on-windows) it is sloooooooooow and it would require to run python under Cygwin, in other words run the agent in Cygwin.

Windows output using `fork` as start method:
<img width="746" alt="image" src="https://user-images.githubusercontent.com/15820737/201340340-615384c8-7c98-4bdf-9d67-d0869c705e12.png">

## Understand how these boundaries affect the Agent

All our objects must be [serializable(pickable)](https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled), anything that is not it will not really run on Windows.
We must base our implementation and design around `Spawned` processes.

## More resources to read on this topic
1. https://rhodesmill.org/brandon/2010/python-multiprocessing-linux-windows/
2. https://stackoverflow.com/questions/42148344/python-multiprocessing-linux-windows-difference

**Comment by ilija-lazoroski** [comment]
Here is a prototype that uses a different version of pandas for two sets of plugins. We agreed to use `Spawned` processes which work well on both Linux and Windows for the prototype.

To install the different versions of pandas run `install_pandas.sh` on Linux and `install_pandas.bat` on Windows.

[multiprocessing-test-spawn.tar.gz](https://github.com/guardicore/monkey/files/10001728/multiprocessing-test-spawn.tar.gz)
