### ISSUE TITLE
None of the exploits are successful, InfectionMonkey can scan but not connect to any nodes

### ISSUE THREAD

**Issue by throwaway180** [guardicore/monkey#2587]
I currently have a VM deployment and am running InfectionMonkey 1.13 to attack it. I copied and pasted the command to manually run it in my Linux terminal. In the infection map, all of the nodes can be found and InfectionMonkey successfully scans them (there are yellow edges from the current node to every other node) but no tunnels are established and all of the exploits fail. From the current node, the other nodes do not require a password to ssh into them so at the very least, SSH brute-forcing should be successful. 

Under the "Exploits" section of the InfectionMonkey UI, I've tried adding the usernames to the "Exploit user list" and I also tried removing all passwords from the "Exploit password list" but neither worked. 

Is there anything else I should try? I've attached my agent log. 
 
Thank you!
[user-1563.txt](https://github.com/guardicore/monkey/files/10021860/user-1563.txt)

**Comment by mssalvatore** [comment]
@throwaway180 There are a number of reasons this could happen. I'm assuming you're using the latest release (1.13.0)? Since you say you have passwordless SSH set up, my first guess is https://github.com/guardicore/monkey/issues/1882.

Can you attach the agent log? You should find it at `/tmp/user-1562`.

You can [join our slack workspace](https://join.slack.com/t/infectionmonkey/shared_invite/enQtNDU5MjAxMjg1MjU1LWM0NjVmNWE2ZTMzYzAxOWJiYmMxMzU0NWU3NmUxYjcyNjk0YWY2MDkwODk4NGMyNDU4NzA4MDljOWNmZWViNDU) for quicker responses.

**Comment by throwaway180** [comment]
@mssalvatore Thank you for the response. Please see my updated post.

**Comment by mssalvatore** [comment]
I'm not sure that just removing the extension will solve the problem. PEM is a different file format.

It looks like this might be related to https://github.com/paramiko/paramiko/issues/2020 and https://github.com/paramiko/paramiko/issues/2017.

I can see from your logs that you're using OpenSSH 7.6, which is [< 7.8](https://github.com/paramiko/paramiko/issues/2017). We're using paramiko 2.9.2, so there may be an issue there.

**Comment by mssalvatore** [comment]
Upon further inspection of the logs, key-based authentication is failing, but password-based authentication is successful. Propagation is failing with the message:

```
2022-11-16 12:53:03,858 [3144214:140006801655616:INFO] sshexec._exploit_host.165: Can't find suitable monkey executable for host VictimHost('172.0.0.10')
2022-11-16 12:53:03,858 [3144214:140006801655616:INFO] monkey.try_exploiting.411: Failed exploiting VictimHost('172.0.0.10') with exploiter SSHExploiter
```

This is rather odd. I can't tell from the agent's log what the issue might be. Can you attach the log for the Island? It's `monkey_island.log` and it will be found in your [data directory](https://techdocs.akamai.com/infection-monkey/docs/data-directory). Most likely `$HOME/.monkey_island/monkey_island.log`.

**Comment by throwaway180** [comment]
I tried updating to OpenSSH 8.9 to address the version issue, but unfortunately it's still not working.

I've attached my monkey_island.log file 

[monkey_island.log](https://github.com/guardicore/monkey/files/10034304/monkey_island.log)

**Comment by mssalvatore** [comment]
@throwaway180 Sorry, I dropped the ball on this. I didn't realize you had responded with your log. I'll take a look as soon as I can.

**Comment by mssalvatore** [comment]
From the Island log:

```
2022-11-16 12:48:30,061 - monkey_download.py:67 - get_monkey_executable() - WARNING - No monkey executables could be found for the host os or machine or both: host_os: linux, machine: please login as the user "azureuser" rather than the user "root".
````

The issue is that the cloud instances are configured not to allow the root users to run any commands over SSH. As a result, the attacking agent is able to successfully authenticate to the victim machine, but can not run any commands.

There is work in progress to help surface this information in a clearer way for the user.

**Comment by throwaway180** [comment]
I added azureuser before to the exploits user list earlier but once I deleted root, it started working. Thank you for your help!!
