### ISSUE TITLE
Automatically check requirements.txt files and package.json

### ISSUE THREAD

**Issue by ShayNehmad** [guardicore/monkey#294]
## Expected Behavior
At CI, automatically scan for new packages that are imported in Python or JS to see if they are satisfied via the requirements.txt files or the package.json file (maybe with `pipreqs`).

## Actual Behavior
Doesn't happen and a developer might forget the new requirement when committing new code with new deps to the repo. 

Relates to #291

**Comment by ShayNehmad** [comment]
https://medium.com/python-pandemonium/better-python-dependency-and-package-management-b5d8ea29dff1

**Comment by danielguardicore** [comment]
@ShayNehmad that will be neat when we have a CI, because we currently have 3 different requirement files :(

**Comment by VakarisZ** [comment]
Seems easy to solve and the sooner we do this the better. If you missed adding dependency to requirements.txt, you'll only notice this during testing of the finished binaries, which is time wasted. This should complement #789 . Possible solution [here](https://stackoverflow.com/questions/16294819/check-if-my-python-has-all-required-packages)

**Comment by VakarisZ** [comment]
This is already partially solved by #1106, because devs now have to install requirements via pipenv and those requirements will end up in pipfile and lockfile automatically (no need to manually edit requirements.txt, so we won't forget). Regarding packages, I don't see how one would forget to commit changed packages.json and package-lock.json. @mssalvatore can we close this?

**Comment by mssalvatore** [comment]
Everything that @VakarisZ said, plus we're building all packages and running automated tests nightly. Closing this.
