### ISSUE TITLE
Reduce risk of #2049

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3041]
# Spike

## Objective
Reduce the risk associated with #2049

## Scope
Time bounded (1.25d) @VakarisZ 
- Understand the proposed solution in #2049
- Consider how we can use `flask-security-too` accomplish #2049 (consider prototyping)

## Output
Tasks, information, or prototypes added to issue #2049
Questions we want anwered:
 - Can MFA or other Flask-security-too features be leveraged to implement one-time password functionality?
 - Should agents be registered as separate users or should agents be sessions of a single agent user? 
     - What steps do we need to take/what code changes are required to accomplish that?
     - Investigate if we can keep the tokens or do we need to migrate to session ID's for authentication
 - Document other tasks required, like role decorator addition
 - Investigate how to test the OTP

**Comment by VakarisZ** [comment]
Potential ideas on how OTP could be combined with the MFA (https://passlib.readthedocs.io/en/stable/narr/totp-tutorial.html#overview):

The `flask-security-too` has to setup `TOTP` for users if we enable MFA. Potentially this can be used in the following way:
1. Setup MFA on flask-security-too
2. Skip MFA for the island user. This can be done in a few ways. When the island user registers or logs in generate and use the generated OTP **OR** override some methods to not request the OTP.
3. When an agent requests the OTP generate one for the island user and provided that. 
4. Then a new agent user wants to retrieve the security token. Verify that OTP the new agent provided was generated by the island user.

This workflow could leverage the OTP infrastructure set up by `flask-security-too`. Optionally we could also just straight up use the passlib as it's already a dependency, but it would require manual setup. Implementing the OTP generation ourselves is probably the worst out of the options possible.

**Comment by VakarisZ** [comment]
High-level ideas about Token vs SessionID:

Session ID:

- We have to extract session ID's from the response. I'm not sure how we can configure the flask-security to return a session ID instead of including it in the cookie (we can't send a cookie because that could cause CSRF in case someone built their own interface) 
- We have to refactor the token based code
- No potential for different agents with different roles
+ Potentially easier OTP distribution, because we can generate OTP's for Agent user
+ Potentially easier cleanup, as agent can just query the logout

Token authentication:

- We have to create/delete the agent user manually (harder setup and cleanup)
- OTP mechanism becomes more complex (for which user do we generate the OTP? how to verify?)
+ Per-agent permissions potential

For more details I'll try prototyping if there's enough time

**Comment by VakarisZ** [comment]
Testing the OTP:

Test cases we want covered:
- [ ] OTP received, agent can use it to authenticate (this will get covered by BB tests, no changes needed)
- [ ] OTP timeout expired, OTP is no longer usable
- [ ] OTP got used, it's impossible to fetch another token with the same OTP
- [ ] Agent finished, the security token he used is now invalid
- [ ] Agent heartbeat timed out. The token is invalidated.
We'll have to write UT's for the resources, but most code is in other packages. We can either write integration tests or test manually. Optionally we could add a manual run test to the BB suite.
