### ISSUE TITLE
Authentication token renewal

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3079]
# Spike

## Objective
1. Users shouldn't be logged out automatically while they are actively using the Island.
2. Agent's shouldn't suddenly be unable to contact the Island when their authentication tokens expire

Understand how we can achieve this with `flask-security-too`

## Output
A new issue that describes the modifications that need to be made to the Island.

## Time Remaining
0d - @VakarisZ

**Comment by VakarisZ** [comment]
There's an option of `REMEMBER_COOKIE_REFRESH_EACH_REQUEST`, but we don't want to store the cookies...

**Comment by VakarisZ** [comment]
I've opened an [issue](https://github.com/Flask-Middleware/flask-security/issues/774) on `flask-security-too` to ask for guidance. If they seem thrilled by the idea of refreshing the tokens server side we should open up a request and implement that on the flask-security-too. If not, we should go with the route of a custom refresh endpoint.

**Comment by VakarisZ** [comment]
Based on the discussion with the maintainers of `flask-security-too` it seems that the intended way to avoid stale tokens is to revoke them on the server side. That being said, if we don't trust our server-side code to do the revocation, there are two options to revoke stale tokens:

## Generate our own refresh token:

We could generate a token that's exactly the same as the authentication token, but with an extended lifespan (we need to use a custom `TimestampSigner` that uses not the current time, but current time + `REFRESH_TIMEDELTA` as it's timestamp). The only difference between the authentication token and the refresh token would be that the refresh token has a longer lifespan. Then, we would add another endpoint. 

Pros: Easier refresh procedure for the client. Does not rely on the flawed "refresh" behavior of the `flask-security-too` (there's risk that this refresh behavior will be changed)
Cons: We need to generate a token manually (complexity, manual work if `flask-security-too` changes their interface or the structure of the token)

Tasks:
 - [ ] Create a refresh token (1.25d)
 - [ ] Modify login and registration to return refresh token (0.5d)
 - [ ] Add logic to the agent to use the refresh token (0.5d)
 - [ ] Add logic to the UI to use the refresh token (0.5d)
 - [ ] Adjust the times for refresh and authentication token (0.25d)


## Adjust the clients to refresh the token `flask-security-too` way.

We would change the Agent to periodically fetch a new token using the old one.

Pros: Cheaper
Cons: Clients have to know about the token lifespan (hard code this value, because it's not present in the token), this refreshing procedure seems flawed and risks being removed (that's my opinion at least). 

Tasks:
 - [ ] Create a "refresh_token" method in `HTTPIslandAPIClient` that would refresh the token for the agent (0.5d)
 - [ ] Make sure that "refresh_token" is being called before each and every usage of `self._http_client` (0.5d)
 - [ ] Cache "refresh_token" for a period of time shorter than the token lifespan (0.5d)
 - [ ] (Optional) Repeat the same procedure for the UI
 - [ ] (Optional) Create an endpoint that would return the token lifespan. This way the client doesn't need to hard-code the refresh time
