### ISSUE TITLE
MITRE ATT&CK - link T1110 to using brute-force exploiters

### ISSUE THREAD

**Issue by itaymmguardicore** [guardicore/monkey#328]
Currently, the 'T1110' attack technique is associated explicitly with each exploit which is a brute force exploit.

We should change the exploit class such that each exploit sub-class will specify whether it's a brute-force based exploit, and/or vulnerability based exploit.

We should discuss whether being a brute-force exploit is a binary state where the opposite is a vulnerability based exploit, or enable both or neither of them to apply to an exploit.

After doing so, we should modify the way we choose which exploits to run. One way can be adding a `should_exploit` function to `HostExploiter`, which checks whether the exploit should be used or not, based on the config and info about target machine.

T1110 should be linked to a config value deciding whether to use brute-force exploits or not.

**Comment by itaymmguardicore** [comment]
`HostExploiter` already has `EXPLOIT_TYPE`. We should either use it, or modify it for this feature

**Comment by VakarisZ** [comment]
I don't understand what this enhancement will solve. When implementing new exploiter you still need to make sure it is linked to attack techniques. So you either have to add all of the techniques it uses (as it is right now) or add some and then search the config to see if there is a dedicated value for it instead. What is more this change would make configuration ambiguous, because `use_brute_force` config value would not disable exploiters. Lastly I'm not fond of this 'lets add dedicated config values for each technique' approach, because by the end of attack matrix we will have 100 config values that are ambiguous and pain to use. Instead, maybe we should consider sending the matrix config to monkey.

**Comment by VakarisZ** [comment]
I still don't think it's worth to do extra work JUST so that when you implement new brute-force exploiter you wouldn't have to tag "T1110". This could be revisited once island is able to parse monkey code to actually see `EXPLOIT_TYPE`

**Comment by VakarisZ** [comment]
https://github.com/guardicore/monkey/issues/595 describes a better solution to the problem, then adding a new configuration value for each exploiter type. The issue of having to tag T1110 to new brute force exploiter can be neglected, as you still need to review/tag other attack techniques.
