### ISSUE TITLE
UI Analytics

### ISSUE THREAD

**Issue by ordabach** [guardicore/monkey#3684]
# Spike

## Objective
Find a solution to collect data about the user behavior (e.g.: buttons clicked, time spent on each page, time spent in the app, etc.).
If there's a tool that will also generate user journeys that will be beneficial.

## Scope
1-1.5 days

**Comment by shreyamalviya** [comment]
## [react-tracking](https://github.com/NYTimes/react-tracking)
**Activity**
- Last release: v9.3.2 on 25 May 2023
- Last commit to `main` branch: 19 July 2023

**What I like about it**
1. Easy to add to existing code, can be used as decorators and hooks (and simply by wrapping functions but that's not pretty)
1. No changes to the code required (except perhaps the URL where tracking data requests are sent) if we ever want to change our database/analytics platform
1. We can define what we want to do with the tracking data in one top-level `dispatch()` function, nothing else needs to worry about it

**What I don't like about it**
1. We'll have to set up a database where the tracking data will be sent and stored
1. We'll have to figure out how to organize that data for analysis
1. We need a way to identify requests by user (random ID at initialization? IP?)

**Resources**
- [Their README gives a really good overview of its usage](https://github.com/NYTimes/react-tracking)
- [Their official blog post explains its working well](https://open.nytimes.com/introducing-react-tracking-declarative-tracking-for-react-apps-2c76706bb79a)

---

## [Countly](https://countly.com/)
**Activity** (on relevant SDK's repository)
- Last release: v22.06.0 on 22 November 2022
- Last commit to `master` branch: 3 April 2023

**What I like about it**
1. Storage and backup of tracking data, upgrades, etc all handled (unless we self-host Countly)
1. We don't have to worry about organizing data for analysis
1. Allows tracking more kinds of events like tracking how much time is spent on each part of the application, timing events, sending user feedback events

**What I don't like about it**
1. Paid for our use case (we need an SDK which is only available in the paid plan, will have to talk to connect with someone for an estimate)
1. Tracking code is interwove with application code, we need to explicitly send events from inside functions/components that we want tracked (using `Countly.add_event()` and such)

**Resources**
- [Documentation for SDK that we'll use](https://support.count.ly/hc/en-us/articles/360037442892-NodeJS)
- [GitHub repository for the SDK](https://github.com/Countly/countly-sdk-nodejs)

---

## [Mixpanel](https://mixpanel.com/home/)

**Activity** (on relevant SDK's repository)
- Last release: 28 April 2023
- Last commit on master branch: 28 April 2023

**What I like about it**
1. Storage and backup (up to 6 months) of tracking data all handled
1. We don't have to worry about organizing data for analysis
1. Allows tracking more kinds of events like tracking page views, timing events
1. Allows custom events and properties, lots of ways to organize/sort/view collected data in the UI ([example of user activity flow report](https://docs.mixpanel.com/docs/analysis/reports/flows ))
1. User identity management seems easy
1. Good documentation (see [this](https://docs.mixpanel.com/docs/tracking/reference/javascript) and [this](https://github.com/mixpanel/mixpanel-js/blob/master/doc/readme.io/javascript-full-api-reference.md#mixpanel))
1. Has a free plan (seems unlikely that we'll need to opt for the paid plan)

**What I don't like about it**
1. Tracking code is interwove with application code, we need to explicitly send events from inside functions/components that we want tracked (using `mixpanel.track()` and such)

**Resources**
- [Quickstart guide for the relevant SDK](https://docs.mixpanel.com/docs/tracking/javascript-quickstart)
- [GitHub repository for the SDK](https://github.com/mixpanel/mixpanel-js)

**Comment by shreyamalviya** [comment]
## `react-tracking` + Mixpanel

Mixpanel can also generate reports from events by: 
- ingesting events from an Amazon S3 bucket, see [this](https://docs.mixpanel.com/docs/tracking/integrations/s3-import)
- ingesting events from Google Cloud Storage, see [this](https://docs.mixpanel.com/docs/tracking/integrations/gcs-import)
- accepting events through its API, see [this](https://docs.mixpanel.com/docs/tracking/http-api)

One of `react-tracking`'s "what I don't like about it" points is that we'll have to store and organize the data on our own. This solves that problem. We can simply send events using `react-tracking` and use Mixpanel to store and organize the data for analysis. Some effort will be required to figure out the best way to segregate, track, and structure events so that we can fully use Mixpanel's features.

**Comment by VakarisZ** [comment]
Analytics is good for seeing features that we don't need, but for users' hopes we can add #3811

**Comment by shreyamalviya** [comment]
We still need to discuss the options and come to a decision. Google Analytics is quite similar to Mixpanel. We can do some research about which is better if we decide to go down that route.

**Comment by cakekoa** [comment]
Some notes after using all the options:
- react-tracking offers useful syntax for sending events, and can be used to send events to any of the analytics platforms
- Most of the options also automatically track several metrics:
    - Page views
    - Unique users
    - Location
    - ...
- Most if not all options require tracking to be enabled in the browser. The ones with a custom SDK may be able to get around this

#### Google Analytics (GA):
- Need to create custom dimensions/metrics in order to report from custom events
    - Dimension: string describing what happened
    - Metric: Numeric value, can be aggregated
- Reports are flexible, however events need to be flatly structured (key:value pairs) and some things require creative approaches in order to report (e.g. Plugin usage: Multiple events, or csv string and pattern matching)

#### Countly
- Has a free self-hosted version: Countly-Lite
    - Need to set up own domain name, or host it via some method
- Events are limited in a similar way to GA: they need to be in a flat structure (no arrays or objects)
- Reporting seems more limited than GA in the free version, and about the same in the Enterprise version
- Has a server-side SDK (e.g. node server) and a web SDK

#### Mixpanel
- Fairly easy to create reports
- Allows for objects as values in custom events
- Allows reports to be built with nested structures in custom events
- Can be used with Google Tag Manager
- Only 5 reports with the free account

#### Umami
- The self-hosted version is FOSS
- Very easy to setup and use
- Allows for arrays an objects in custom events
- Does not currently allow one to build a report using custom events

**Comment by ordabach** [comment]
Well, it's time for a decision.
We can always change it if we decide to.

What's the easiest solution with fewer restrictions?

**Comment by ordabach** [comment]
https://github.com/guardicode/monkey-analytics/blob/prototype/TODO.md
