### ISSUE TITLE
Design a data exfiltration payload

### ISSUE THREAD

**Issue by mssalvatore** [guardicore/monkey#3773]
# Spike

## Objective
Design a data exfiltration payload. Define:
- [x] How should data be exfiltrated (i.e. what protocol/mechanism is used)?
- [x] Where should data be exfiltrated to?
- [x] What options should the user have to configure it?

Be sure to research data exfiltration tactics and techniques and propose a high-fidelity solution with the most valuable features.

## Scope
Timeboxed: 4d

## Output
- [x] A design document detailing the module's features and the rational behind them
- [x] GitHub issues tracking the work to be done

**Comment by ilija-lazoroski** [comment]
Data exfiltration

Also known as data extrusion or data exportation is data theft: intentional, unauthorized, covert transfer of data from a computer or other device.

Data exfiltration may be conducted manually or automated using a malware (in our case a friendly one).

Data exfiltration vs. Data leakage vs. Data breach

Data leakage is accidental exposure of sensitive data. Data leakage can result from a technical security vulnerability or procedural security error.


Data breach is any security incident that results in unauthorized access to confidential or sensitive information. Someone who shouldn’t have access to sensitive data, gains access to sensitive data.


Data exfiltration is the discrete act of stealing the data. All data exfiltration requires a data leak or a data breach. It is not data exfiltration until the data is copied or moved to some other storage device under the attacker’s control.


MITRE Techniques regarding our payload ( https://attack.mitre.org/tactics/TA0010/)

T1020 - Automated Exfiltration
T1030 - Data Transfer Size Limits (In the past we encountered size limits in SNMP, so if we decide to spend time this will be a good one)

If we decide to use any protocol other than the Island : T1048 - Exfiltration Over Alternative Protocol

There may be one or two more for our specific case but I won’t get into them now.


Plan

Victim sends data, attacker receives the exact same data.

We need to be able to send the data to a specific endpoint which we are going to create on the Island. 

As options I purpose for simplicity a Linux and Windows directory in which we will try to get all the files back to our monkey directory under folder named exfiltrated_data. If we want we can also add recursive option but I won’t go down that route.

We should probably implement Data Transfer Size Limits as that will save use from network limits problems.

The payload check the permissions of the directories. List the contents, gets each file with specific extension (similar to ransomware) and sends it by chunks to some endpoint DataReciever or HTTPDataServer.

That endpoint will use a service DataExfiltrationService  which will need to construct/update a file in that exfiltrated_data directory under monkey dir.

Note: The construction may not be needed if we decide that we don’t care about transfer limits of the file. 

More important note: The endpoint or a server may be used outside of the payload and fill the system with unneeded data.

Similar to the ransomware but probably we will wait for the reporting to be improved we will need to report which files were exfiltrated from which victim machine.

We should probably set limits to how much data can be received to avoid unneeded data on the Island machine.

If we decide to not use the Island API and use some other protocols to get the data then we can choose which one but I am not sure if that is a good idea because those protocols need to be running on the Attacker Machine (Island). 

For Linux we can use: HTTP/S or FTP/S
For Windows: Net/SMB or FTP

**Comment by acepace** [comment]
> As discussed on Webex, I think it's unlikely that exfiltrating data to the Island is of the highest value. I'm under the impression that the most common technique is to exfiltrate data to an S3 bucket, though I could be misinformed on that. Let's find some literature that helps us determine the most common way(s) that data is exfiltrated.

I'd suggest a bunch of ways

* DNS exfiltration, where you put the data as a sub record and do a DNS lookup to a byte or two bytes of data
* Upload to social media, such as Discord or Twitter as C2 channels or exfil methods
* Upload to shared drives such as Dropbox/GDrive/OneDrive
* Upload to anonymous S3 buckets (whether open/breached ones or attacker controlled ones)
* Upload to an open proxy that sends the data to the real target

More ideas? :)

**Comment by mssalvatore** [comment]
I got the following feedback from a user/stakeholder:

## Exfiltration mechanisms
- Exfil to an S3 Bucket
- Exfil via SSH/SFTP

## File Selection
- Allow the user to specify a root directory (e.g. C:\, \\my-smb-share\dir, /home)
- Provide a checkbox for whether search should be recursive
- Allow the user to specify file extensions

## Other features
### Exfiltrate massive quantities of data
Data exfil is often not very targeted. Attackers are attempting to exfiltrate as much data as quickly as possible so they can analyze it later. A feature that would allow large quantities of data to be exfiltrated (even if the plugin was generating random data) would be valuable

### Data generation
Generating data (e.g. fake social security numbers or credit card numbers) would really help test out data exfil detection tools.

**Comment by ilija-lazoroski** [comment]
> I got the following feedback from a user/stakeholder:
> ## Exfiltration mechanisms
> 
>     * Exfil to an S3 Bucket
> 
>     * Exfil via SSH/SFTP
> 
> 
> ## File Selection
> 
>     * Allow the user to specify a root directory (e.g. C:, \my-smb-share\dir, /home)
> 
>     * Provide a checkbox for whether search should be recursive
> 
>     * Allow the user to specify file extensions
> 
> 
> ## Other features
> ### Exfiltrate massive quantities of data
> 
> Data exfil is often not very targeted. Attackers are attempting to exfiltrate as much data as quickly as possible so they can analyze it later. A feature that would allow large quantities of data to be exfiltrated (even if the plugin was generating random data) would be valuable
> ### Data generation
> 
> Generating data (e.g. fake social security numbers or credit card numbers) would really help test out data exfil detection tools.

If we exfiltrate massive quantities of data, then we will probably need to implement Data Transfer Size limit as well. 
This may need to be done to avoid network data transfer thresholds.

**Comment by ilija-lazoroski** [comment]
> As discussed on Webex, I think it's unlikely that exfiltrating data to the Island is of the highest value. I'm under the impression that the most common technique is to exfiltrate data to an S3 bucket, though I could be misinformed on that. Let's find some literature that helps us determine the most common way(s) that data is exfiltrated.

I couldn't exactly find some literature of the most common way(s), probably because as you said they only care to take as much data as fast as possible and not too much around the protocol used behind it.

What I could find was just an examples of what it was actually used. To sum up, the order is this list is not really by what is most used protocols:

- HTTP/HTTPS
- DNS
- SMTP
- FTP
- TCP
- SMB
- SSH
- ICMP
- SSH
- RDP

From the cloud environments:

- Amazon S3
- Google Cloud Storage
- Azure Blob Storage
- Exposed API on cloud environment
- Cloud-based Message services

So I am okay with the feedback that we got from the user/stakeholder. We need to webex and design it, so we can write the issues.

**Comment by ilija-lazoroski** [comment]
Issues created: #3888, #3887 and #3886
