### ISSUE TITLE
Target Directories from Ransomware plugin are broken

### ISSUE THREAD

**Issue by ilija-lazoroski** [guardicore/monkey#4000]
## Describe the bug
Some package updates happened in the UI, possibly leading to target directories being shown as options in the Ransomware plugin. This could be happening in other plugins as well. 

## To Reproduce
1. Install Ransomware plugin
3. See the error in the configuration page

## Expected behavior
It should be an input, not an option.

## Screenshots
<img width="1163" alt="image" src="https://github.com/guardicore/monkey/assets/15820737/84388fc9-b41a-42b0-904a-6b3363cdd2f5">

It seems that it has something to do with how the field is represented in the options. We have Optional field with a default value of None. If we remove the Optional part then:
<img width="1228" alt="image" src="https://github.com/guardicore/monkey/assets/15820737/6736e661-495b-4087-be06-b916b283666b">

If we leave the Optional part and add a different default value:
<img width="1208" alt="image" src="https://github.com/guardicore/monkey/assets/15820737/7aed6799-fe9b-4b84-8163-c88b8bbb1b8a">

I am guessing Optional means Option? 😄 

## Machine version (please complete the following information):
 - OS: Windows or Linux

**Comment by cakekoa** [comment]
The problem is that we updated the plugin build script to generate the config schema based on the options model. Before this, the schemas were generated manually. Now the build script uses pydantic's [model_json_schema](https://docs.pydantic.dev/latest/api/base_model/#pydantic.main.BaseModel.model_json_schema) to generate the schema.

The ransomware target directory options are nullable types. The manually generated schema modeled this by using `["null", "string"]` as the type of the field. The pydantic generated schema uses `anyOf` with one of the options as `type: null`. This `anyOf` is rendered by RJSF as a dropdown list.

[Pydantic issue](https://github.com/pydantic/pydantic/issues/7161) discussing `anyOf` for nullable types

**Comment by cakekoa** [comment]
Potential solutions:

1. Provide a manually generated schema for Ransomware, and update the build script to only generate the config schema if one doesn't already exist
1. Use a custom generator that flattens out the `anyOf` when generating the schema
1. Flatten out the `anyOf` in the Island UI when retrieving the schema from the API
1. Submit a PR to RJSF to handle this `anyOf` case

**Comment by mssalvatore** [comment]
Sounds like #1 is perhaps the best approach. There may be other reasons in the future we would want a custom schema. Let's just make sure the build script prints a visible warning (use colors if possible) that warns when the schema is not regenerated.

**Comment by ilija-lazoroski** [comment]
> Sounds like #1 is perhaps the best approach. There may be other reasons in the future we would want a custom schema. Let's just make sure the build script prints a visible warning (use colors if possible) that warns when the schema is not regenerated.

![image](https://github.com/guardicore/monkey/assets/15820737/f03e7da4-6d4e-4b51-8a9d-6d8950a79db6)
Something like this?
