### ISSUE TITLE
Add `_Sidebar.md` and `_Main.md` files to our Wiki

### ISSUE THREAD

**Issue by ShayNehmad** [guardicore/monkey#516]
**Is your feature request related to a problem? Please describe.**
Want to make our wiki look better.

**Describe the solution you'd like**
Here's an example: https://github.com/nccgroup/ScoutSuite/wiki

**Comment by dhaval0894** [comment]
Hi @ShayNehmad, I have taken up this issue and have added the `_Sidebar.md`. I tried adding `_Main.md` but it didn't make a difference since there's already a `Home.md`. As it's for a Wiki, I didn't find any way to raise a pull request - [How to pull request a wiki page on GitHub?](https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github).  Link to my [Repo](https://github.com/dhaval0894/monkey-wiki).

**Comment by ShayNehmad** [comment]
Moved to https://www.guardicore.com/infectionmonkey/docs/
