### ISSUE TITLE
Require a specific environment for the working of exploits for Linux

### ISSUE THREAD

**Issue by ashish493** [guardicore/monkey#572]
As this tool is mainly focused on exploiting the Windows system ( yeah, also for the servers), It would be much better if we add the same for Linux..

**A Possible Solution:-**
No ideas at present..

**Comment by ashish493** [comment]
Any suggestions are welcome? As I still don't have a specific working idea for the solutions.

**Comment by VakarisZ** [comment]
You meant to say that, the problem is that we can't add exploit written in C for example? Or that it's hard to add a new exploit? I don't really understand what's the issue. You can add exploiter and add the corresponding configuration to the configuration. Infection monkey is not metasploit, it doesn't aim to exploit specific system with a specific exploit that has specific configuration. User shouldn't spend time configuring exploits, they should be automatically configured.

**Comment by ashish493** [comment]
Sorry for the wrong description of the issue,
Actually, I was discussing some ideas with @ShayNehmad and he suggested me to add a feature request, regarding this features and also for making the exploits run for Linux..

Well, I was wrong for the metasploit part, because of the reason you described here..

So, I am modifying this issue...

**Comment by ShayNehmad** [comment]
Hi @ashish493,
Since I'm not sure what's the actual feature request here (since Monkey does exploit and run on Linux as well) I'm closing this ticket. 

If you wish to create a separate, more specific issue for implementing CVE-2019-4279, I'd encourage you to do so. In general, try to make the issue as specific and as understandable as possible.
