### ISSUE TITLE
Improve current Configuration UI

### ISSUE THREAD

**Issue by ShayNehmad** [guardicore/monkey#637]
This includes vastly improving the UI of configuring stuff in the Monkey.
This does NOT include added a wizard/scenarios feature, only improving the current layout content.

- [ ] Document each config value with examples in the #602.
- [x] #595
- [x] #526
- [x] #566 
- [x] Add validation to fields like network segments (possibly convert `Form` to `Formik`)

**Comment by VakarisZ** [comment]
We should aggregate all config-related problems into one issue and then see how many of them and which ones we should solve. We should also set some time to review the configuration and maybe move/hide some values or implement other changes that would improve configuration process.

**Comment by VakarisZ** [comment]
# Todo list (Pending):

# Global changes:

- Instead of "Basic - ..." we should highlight essential tabs with green colour.
- Create a mix of dropdown and checkmark component. On click checkmark is marked
 and dropdown is displayed.
- Create an advanced selector, that allows to select/deselect on click. On click 
information about clicked property is shown in selectors info pane. Advanced selector
also has space for custom buttons.


## Basic - Exploits

- Should be renamed to Credentials

### General

- "Exploit network machines" is removed (moved to exploiter selector)

## Basic - Network

- Should be renamed to Network

### General 

- Should be renamed to "Scope"

Contains:
- "BlockedIPs"
- "By depth" (selected by default) - dropdown AND checkmark component.
- "By scope" - dropdown AND checkmark component.

#### By depth
- On click "Depth" input is displayed and "Local network scan" value is enabled.
- "Local network scan" UI is hidden.

#### By scope
- On click "Scan IP/subnet list" is displayed.
- "Local network scan" value is disabled.

## Monkey

### Behaviour

- "Self delete on cleanup" - moved to Internal/Monkey (on by default).
- "Serialize config" - moved to Internal/Monkey (off by default).
- "Use file logging" - moved to Internal/Monkey (on by default).
 
### General

- "Is monkey alive" - hidden.
- "Post breach actions" - advanced selector with info pane that displays 
what each post breach action does.

### Lifecycle

- Renamed to "Persistent scanning"
- "Retry failed exploitations" - moved to "Internal/Lifecycle".
- "Max victims to exploit" - removed. Scope is alredy defined is "Scope".
- "Max victims to find" - removed. Scope is already defined in "Scope".

- Dropdown checkbox component also named "Persisten scanning" is added. Disabled by default. 
When disabled, "Max iterations" is set to 1.

#### Persisten scanning

- "Max iterations" - set to 2 on "Persistent scanning" toggle.
- "Wait time between iterations" - unchanged.

### System info

- "System info collectors" refactored into advanced selector component.
- "Collect system info" - removed. Same can be achieved by disabling all collectors.
- "Should use mimikatz" - refactored into Mimikatz system info collector.
- "Harvest Azure credentials" - refactored into system info collector.

## Monkey Island

### Servers

- Whole "Servers" section moved to Internal. "Command servers" uses all local interfaces
which is a reasonable default. "Current server" is also chosen automatically/doesn't matter.

### Internet services

- Section either moved to "Monkey/Behaviour" or to internal.

## Network

- Whole tab moved to internal

## Exploits

- Tab moved to be after "Network"
- Everything in this tab except "Exploits" are moved to "Internal". 

### General

#### Exploits

- "Exploits" made into advanced selector. Info pane displays information about exploiters, there is a button 
"Don't exploit" that de-selects all exploiters.

## Internal 

- Refactored into sub-tabs or dropdowns for each section.
