### ISSUE TITLE
Dockerfile gets 404 since deb isn't in release, need to update to deploy source

### ISSUE THREAD

**Issue by christiandgv** [guardicore/monkey#641]
## Describe the bug
when try up monkey with docker compose not found repo.
 Step 7/11 : ADD https://github.com/guardicore/monkey/releases/download/${RELEASE}/infection_monkey_deb.${RELEASE}.tgz .
ERROR: Service 'monkey' failed to build: ADD failed: failed to GET https://github.com/guardicore/monkey/releases/download/1.8.0/infection_monkey_deb.1.8.0.tgz with status 404 Not Found: <!DOCTYPE html>
<html lang="en">

## To Reproduce
1. copy and paste in your browser https://github.com/guardicore/monkey/releases/download/1.8.0/infection_monkey_deb.1.8.0.tgz 
3. See error

## Expected behavior
A description of what you expected to happen.

## Machine version (please complete the following information):
 - OS: Windows or Linux

**Comment by ShayNehmad** [comment]
Hi, we actually need to update the docker-compose script to deploy using the code, instead of the precompiled `deb` option. 

Until we get to that, you can download the .deb option from the [Infection Monkey site](https://infectionmonkey.com) and plug the link you'll get there. However, we do offer a Docker option there as well, so you could just use that.

**Comment by VakarisZ** [comment]
Issue doesn't make sense to me. Closing until bug is properly described

**Comment by mssalvatore** [comment]
@VakarisZ In order to build the docker container, the `Dockerfile` pulls a .deb from github (which may not exist anymore) and uses it to install Monkey Island into the container. Instead. we should be building the docker container from source code. This will allow developers and users to build and test containers during development more rapidly.

**Comment by acepace** [comment]
@VakarisZ the best way is to do this multi stage. This should be easy (done it in the past)
one docker container to build the island that passes it off to a docker container to host the island.
This also lets you "easily" use nginx or another front end for certs if the user wishes

**Comment by mssalvatore** [comment]
As far as I can tell, we're not using the `docker/` directory for any of our official builds, nor are any devs using it for development. I've removed this directory in 30add417. We can revert this commit if we need these files back in the future.
