### ISSUE TITLE
Add NMAP vulnerability scanning scripts

### ISSUE THREAD

**Issue by ShayNehmad** [guardicore/monkey#660]
Will add a lot of vuln scanners to the reports etc.

**Comment by acepace** [comment]
Do we want to have this as a subprocess call and carry nmap or do we want to integrate the nmap engine?

**Comment by VakarisZ** [comment]
We need to check the licensing prior to starting the feature.

**Comment by acepace** [comment]
Free nmap doesn't allow bundling in commercial tools, need a lawyer to go over and say if Infection Monkey applies or not

**Comment by VakarisZ** [comment]
A lot of options, but none ideal. We could try to build our own fork with only the things we need, because my idea was to include nmap for safe vulnerability scanning scripts, not for network discovery. Or maybe the binaries are not that bad + easy to update. Without doing more in depth investigation I can't tell which is the lesser evil.

**Comment by mssalvatore** [comment]
If NMAP doesn't work out, this is another option: Something like this might help: https://github.com/robertdavidgraham/masscan

It doesn't have all of the same benefits as NMAP, but it might be useful in other ways.

**Comment by VakarisZ** [comment]
This issue is about a trivial way to add safe vulnerability scanning. Nmap had +30 safe vuln. scanning scripts at the time, that's why I came up with this idea.

**Comment by mssalvatore** [comment]
For the moment, we want to avoid turning monkey into a vulnerability scanner. Closing for now.
