### ISSUE TITLE
Add "Hidden Files and Directories" attack technique (T1158)

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#672]
**[T1158](https://attack.mitre.org/techniques/T1158/)**

Adversaries can use the concept of ‘hidden’ files (files that don’t show up unless explicitly asked to be seen) to hide files and folders anywhere on the system for persistence and to evade a typical user or system analysis that does not investigate hidden files.

**Adding it as a PBA:**  
This attack technique would require attempting to create a hidden file/folder and then removing it by running a set of commands.  
\- _LINUX_: using a dot ("`.`") before the name of the file/folder to make it hidden; see [this](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1158/T1158.md#atomic-test-1---create-a-hidden-file-in-a-hidden-directory)
\- _WINDOWS_: using the `attrib` command to make a file/folder hidden; see [this](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1158/T1158.md#atomic-test-4---create-windows-hidden-file-with-attrib)

**Mapping the technique to the ATT&CK matrix:**  
Follow [this](https://github.com/shreyamalviya/monkey/blob/guide-to-add-attack-technique/monkey/Adding-a-new-attack-technique.md).

**Comment by ShayNehmad** [comment]
Looks good! 
I have a few questions/suggestions:
- The PBA should cover all of the following cases: 
  - Linux: File with `.`
  - Linux: Folder with `.`, make sure to create some content in it
  - Windows: Create a regular file, use `attrib`
  - Windows: Create a regular folder, use `attrib`
  - Windows: Create a hidden file using the CreateFile [WinAPI function](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfilea).
- How would the "technique selected" element look in the MITRE report? What specifically would we like to show the users? I think a list of all machines with details on WHICH cases worked on which machines could be useful and descriptive.
- We must make sure to remove everything we've created, even if we have an error while running (don't want to leave traces in the users' servers). Therefore perhaps it makes sense to `sleep` for 10 seconds or so after creating all the hidden stuff, just so that AV software has time to find it.
- We should maybe leave one hidden file next to the log? What do you think @shreyamalviya?

**Comment by shreyamalviya** [comment]
- Alright
- Yeah, we can have all machines with the output results of all the cases, highlighting the successful and unsuccessful ones differently.
- Okay
- I'm not sure I understand why we'd do that?

**Comment by ShayNehmad** [comment]
> We should maybe leave one hidden file next to the log? What do you think @shreyamalviya?

Just so that AVs might find it even after the Monkey finished executing... It's nice to have, but on second thought it's not important and probably not worth the mess we'll leave on servers.

**Comment by acepace** [comment]
We don't need to `sleep`. Any decent AV has real time scanning, if it doesn't, that's an issue to escalate to the user of the monkey
