### ISSUE TITLE
High level overview/description of the tool.

### ISSUE THREAD

**Issue by VakarisZ** [guardicore/monkey#871]
### Add a new page 🆕

**What documentation you'd like us to add?**
We need to add a page that gives a high lever overview of the tool. Somehow our contributing and other docs jump straight into fine details without explaining that there's an Island which is a C&C server, there are Monkeys, which are worm like binaries and etc.

**Comment by mssalvatore** [comment]
Some high-level diagrams that show how the monkey propagates, or how the monkey interacts with the island might be useful.

**Comment by shreyamalviya** [comment]
- We should stick to using the same terms everywhere. Sometimes, we refer to Infection Monkey as just "Monkey", which we also use to refer to the Monkey Agent. Could be confusing. Example:<br>
<t><img src="https://user-images.githubusercontent.com/44770317/102878653-96154600-446e-11eb-9703-0359b9d55eef.png" height=120>

- Update the screenshots since the UI has changed quite a bit for Monkey and for Swimm.

**Comment by VakarisZ** [comment]
Yes. We should probably rename "Monkey" to "Monkey agent" when we talk about the binaries.

**Comment by VakarisZ** [comment]
Mostly solved in #1047. If we want to solve something else, we should open up more specific issues
