### ISSUE TITLE
Extract OS information from the TCP scanner

### ISSUE THREAD

**Issue by shreyamalviya** [guardicore/monkey#922]
Extract OS information from the TCP scanner since ping scanner may not always work and all the exploiters depend on that, as of now (see #921 for more details).

**Comment by acepace** [comment]
TLDR

We'll add sockopt for IP information
then use recvmsg to extract the IP TTL and use the same logic as pingscanner

**Comment by acepace** [comment]
So my idea is bunk. We can't get IP headers for SOCK_STREAM (TCP) sockets.

We will either need to use raw sockets (require root) or a setuid binary. 
@VakarisZ what do you think? should I assume root and just do that?

**Comment by mssalvatore** [comment]
What about using different criteria, like window size or segment size? The [nmap os detection db](https://nmap.org/book/nmap-os-db.html) can be used to identify a variety of OS's based on various different criteria.

**Comment by acepace** [comment]
@mssalvatore TTL and Window/Segment size all require
* Root permissions 
* Creating raw IP sockets

The latter means also implementing a basic 3 way handshake ourselves, which is fine.

**Comment by VakarisZ** [comment]
Yep, root is required even when using nmap itself for OS detection.
If you consider that this feature is only valuable when:
1. Ping scanner is disabled or ICMP blocked with firewall
2. Monkey has root (should be pretty common on island, but everywhere else - probably not)
3. The TCP scanner itself is enabled
4. Connection is not NAT'ed?
The value this feature would bring is:
Potentially save some exploitation time, but only in the scenario mentioned before.

Maybe we should opt for a more trivial task to add OS reconnaissance to HTTP finger? Sometimes OS can be deduced from `Server` header.

Also, if we'll include NMAP for safe vuln scanning, we'll get this feature as a bonus (not certainty, but worth considering).

Generally speaking, I still believe that monkey behavior should be "on unknown OS try exploiting both", since it covers all cases. Then we could profile and maybe improve the exploitation time itself, which is also valuable in all cases and achieves the same goal of lowering the exploitation time.

**Comment by mssalvatore** [comment]
My concern with "on unknown OS try exploiting both" is there may be edge cases where something that is safe to exploit on one OS causes a crash or other unforeseen consequences on another OS.

I think this is an acceptable risk only if our integration tests make some attempt to prove that safe exploits are safe for all OSs.

**Comment by acepace** [comment]
@VakarisZ let me try to lay it out.

If TCP scanner is not enabled, we'll anyway have zero information for most exploiters and nothing will happen. Generally, I assume PingScanner is the more optional as ICMP is more likely to be blocked while you can't block TCP without blocking real network functionality.

Regarding Monkey as root, so some of our attacks give us root, others don't. We can easily have a get host port version with root and without. 

Regarding NATed networks, data center networks are rarely NATed. 

Regarding nmap, nmap fingers OSes typically using raw sockets, which again circles back to root.

**Comment by acepace** [comment]
If we assume root, it's no big deal to do a scan with raw sockets on an open socket and get the information. 🤷

**Comment by VakarisZ** [comment]
> If TCP scanner is not enabled, we'll anyway have zero information for most exploiters and nothing will happen.

@acepace "nothing will happen" is the bug. If exploiters are enable they should run. I'm not against implementing TCP scanner, but it won't solve the problem in all cases (opened #940 ). 

@mssalvatore IIRC we don't have payloads depending on OS. What you describe is unlikelly.

**Comment by mssalvatore** [comment]
Unlikely, yes. But if we expect people to run this in their production environments, and we want to assure them that it's safe, we'd better cross all our I's and dot all our T's.

**Comment by acepace** [comment]
@VakarisZ I honestly don't understand. The TCP scanner tells the exploiter if it's worth running. If no scanning happens how can an exploiter work?
Unless you want to drop that model except for report purposes?

**Comment by shreyamalviya** [comment]
This is no longer relevant. The Agent code was refactored.
