### ISSUE TITLE
Messy installation process

### ISSUE THREAD

**Issue by Dviros** [guardicore/monkey#97]
Hey guys,
I'm trying to wrap my head around the installation process:
Currently, your git readme file refers to the Setup page in the Wiki.
The setup page refers to the blog, where there is completely no installation steps.
The only installation steps i've found are in the monkey\monkey_island\readme.txt, and they are messy.

1. I suggest to get all the info in one place.
2. I recommend on creating an installation script for Debian and Ubuntu (using bash).
3. Explaining more on the folders hierarchy as it is unclear.

Thank you very much, can't wait to try it.
Dviros.

**Comment by danielguardicore** [comment]
Hey Dviros, I'll try to improve some of this stuff next week.

For now, If you want to setup a development environment from scratch, check the Wiki page on [Development](https://github.com/guardicore/monkey/wiki/Development). Note, since it requires compiling 4 executables, you'll need build envs for different Windows/Linux versions. This is a limitation of the Python library we're using to freeze the Python code.

**Comment by Dviros** [comment]
Noted. Thanks!

**Comment by danielguardicore** [comment]
Check out some of our improved documentation/package. I also uploaded precompiled binaries and deb to the release tag.
